version: '3.3'
volumes:
  pg_data:
  static:
services:
  db:
    image: postgres:13.16
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    image: nprivezentsev/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static/
    depends_on:
      - db
  frontend:
    image: nprivezentsev/foodgram_frontend
    volumes:
      - static:/app/result_build/build/
  gateway:
    image: nprivezentsev/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/static/
    depends_on:
      - backend
      - frontend
