INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256
RECIPE_SHORT_LINK_CODE_MAX_LENGTH = 3
TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
OBJECT_NAME_MAX_DISPLAY_LENGTH = 64
