INGREDIENT_NAME_MAX_LENGTH = 250
RECIPE_NAME_MAX_LENGTH = 250
TAG_NAME_MAX_LENGTH = 50
TAG_SLUG_MAX_LENGTH = 50
MEASUREMENT_UNIT_MAX_LENGTH = 10
DECIMAL_MAX_DIGITS = 6
DECIMAL_PLACES = 2
OBJECT_NAME_MAX_DISPLAY_LENGTH = 50
