# Generated by Django 4.2.16 on 2024-11-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_name_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite_users',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_cart_users',
        ),
    ]
