# Generated by Django 4.2.16 on 2024-11-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_authors',
        ),
    ]
