# Generated by Django 4.2.16 on 2024-11-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_subscription_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('author')), _negated=True), name='chk_users_subscription_prevent_self_subscription'),
        ),
    ]
